name: Your New Jekyll Site
markdown: redcarpet
pygments: true
# Jekyll Image Tag settings
image:
  source: assets/images/_fullsize
  output: generated
  presets:
    # gallery
    gallery:
      attr:
        class: thumb
        width: 400
    # Proportional preset
    users:
      attr:
        class: thumb
        itemprop: image
      width: 270
    # Scaled and cropped preset
    half:
      width: 400
      height: 400